---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: vars_path

params:
  CLIENT_CREDENTIALS_USER_ID:
  CLIENT_CREDENTIALS_USER_SECRET:

run:
  path: sh
  args:
  - -c
  - |
    set -eux

    cat << EOF > vars_path/vars.yml
    client-credentials-user-id: $CLIENT_CREDENTIALS_USER_ID
    client-credentials-user-secret: $CLIENT_CREDENTIALS_USER_SECRET
    EOF
